### ISSUE TITLE
Motor records neither autosaved nor archived

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/ads-ioc#27]
Some of the motor record fields should be autosave and most of them should be archived. They are currently omitted from the autosave and archive files.

**Comment by klauer** [comment]
This can be addressed by #30, #33 - if we decide that's the direction we want to go.

**Comment by ZLLentz** [comment]
I think this is the right way to go. The only alternative I can think of is to have a separate autosave/archive path specifically for the motors... That sounds awful.

**Comment by klauer** [comment]
Closed by the above-mentioned PRs.
