### ISSUE TITLE
Decide on Autosave path

### ISSUE THREAD

**Issue by klauer** [pcdshub/ads-ioc#32]
`$(IOC_INSTANCE_PATH)/autosave` seems weird, especially since `${IOC_DATA_PATH}/${IOC_NAME}/autosave` already exists.

Should we switch over? I think it was only the above for my testing, but I can't recall...

**Comment by ZLLentz** [comment]
IIRC for all of our IOCs we keep the autosave specification in the build directory and the results in the ioc data area
