### ISSUE TITLE
Repeated errors: "callbackRequest: cbLow ring buffer full"

### ISSUE THREAD

**Issue by klauer** [pcdshub/ads-ioc#68]
Seen in the latest version of https://github.com/pcdshub/lcls-plc-tmo-vac/tree/master/iocBoot/ioc-PLC-TMO-VAC
(not yet pushed as of writing: `/reg/g/pcds/epics-dev/jyin/gitProjects/lcls-plc-tmo-vac`)

Seems like we may need to increase the callback queue size by way of `callbackSetQueueSize` (default may be 2000?)

**Comment by ZLLentz** [comment]
I wonder if this a race condition based on whatever else is running on the server...

Should we set this to something like the number of PVs if we have more than 2000 PVs?

According to EPICS tech talk the main drawback is more RAM used (shouldn't be a big deal):
https://epics.anl.gov/tech-talk/2017/msg00811.php

**Comment by klauer** [comment]
Race does seem a definite possibility, based on what Jing had seen when switching to an IOC host with less load.

Agreed on setting it to something like the number of PVs (or proportional to it). We had another parameter we wanted to do proportionally for asyn, didn't we... Hmm... Will take care of these tomorrow.
