### ISSUE TITLE
Determine task count dynamically for taskinfo.db

### ISSUE THREAD

**Issue by klauer** [pcdshub/ads-ioc#70]
Some users are seeing these messages at startup:
```
2020/12/01 17:04:41.873 adsAsynPortDriver:adsGetSymInfoByName: Get symbolic information failed for TwinCAT_SystemInfoVar                               List._TaskInfo[2].TaskName with: ADSERR_DEVICE_INVALIDARRAYIDX (0x721)
devAsynInt8Array::initCommon, PLC:las_bts:TaskInfo:2:TaskName drvUserCreate failed
```

It appears we don't always have 2+ tasks?

ref https://github.com/pcdshub/ads-ioc/blob/master/app/Db/TwinCAT_TaskInfo.db

**Comment by ZLLentz** [comment]
Do we read it from the tmc/project? Or is there some ADS interface for getting the number of tasks?

**Comment by klauer** [comment]
I took a brief look into the TMC file and didn't see anything regarding tasks; but I assume it's because it's a fairly dynamic thing?

**Comment by ZLLentz** [comment]
I think the number of tasks is predefined in the project, so the information should be in there somewhere

**Comment by klauer** [comment]
Hmm, you're right - this is also useful information for the summary pages:

```
In [9]: list(project.find(Tasks))
Out[9]: [<Tasks children=[<Task name='PlcTask' attributes={'Id': '5', 'Priority': '20', 'CycleTime': '100000', 'AmsPort': '350', 'AdtTasks': 'true'} children=[<Name text='PlcTask'>]>]>]
```

However, for `lcls-plc-kfe-motion` I'd have expected to find more than just one (right?)

**Comment by ZLLentz** [comment]
Probably only one PLC task, but there should be a few NC tasks

**Comment by ZLLentz** [comment]
I suspect most of our PLCs have either 1 task or 2 (fast task and slow task)

**Comment by klauer** [comment]
I think I should tackle this as part of #86 - need to look into this again
